homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 48
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  # base_url: !secret base_url
  # server_port: 443
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key
  #api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 5
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

system_health:

# Weather prediction
sensor:
  - platform: yr
    name: Weather
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - cloudiness
  - platform: template
    sensors:
      day_night:
        friendly_name: "Day and night"
        value_template: >-
          {% if now().hour >= 18 and now().hour < 24 %}
            Evening
          {% elif now().hour >= 0 and now().hour < 8 %}  
            Night
          {% else %}
            Day
          {% endif %}

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

wake_on_lan:
    
switch:
  - platform: wake_on_lan
    name: "Faye's PC"
    host: 192.168.0.20
    mac: "f4:6d:04:48:9f:9c"
#    turn_off:
#      service: hassio.addon_stdin
#      data:
#        addon: core_rpc_shutdown
#        input: fayes_pc
    
  - platform: wake_on_lan
    name: "My PC"
    mac: "E0:D5:5E:20:53:46"
    host: 192.168.0.26
    
#  - platform: template
#    switches:
#      telly:
#        friendly_name: "The TV"
#        value_template: "{{ is_state('switch.hdmi_0', 'on') }}"
#        turn_on:
#          service: script.television_on
#        turn_off:
#          service: script.television_off
#          
#  - platform: template
#    switches:
#      fayes_pc_and_tv:
#        friendly_name: "Faye's PC"
#        value_template: "{{ is_state('switch.just_fayes_pc', 'on') }}"
#        turn_on:
#          service: script.boot_to_fayes
#        turn_off:
#          service: script.turn_off_fayes
   
binary_sensor:     
  - platform: workday
    country: UK
            
emulated_hue:
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - media_player

alexa:

intent_script: !include alexa_intents.yaml

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.18
    home_interval: 10
  - platform: nmap_tracker
    hosts: 192.168.0.28
    home_interval: 10
    
automation old:

  - alias: 'Toggle bedside light from bedroom switch'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_2
        event: 1002
    action:
      service: light.toggle
      entity_id: light.bedside_light

  - alias: 'Turn off all lights from bedroom switch'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_2
        event: 1004
    action:
      - service: light.turn_off
        entity_id: all
      - delay: "00:00:01"
      - service: light.turn_on
        entity_id: light.bedside_light

  - alias: 'Toggle bedside light from smart switch'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bedside_switch
        event: 1002
    action:
      service: light.toggle
      entity_id: light.bedside_light

  - alias: 'Turn off lights from smart switch'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bedside_switch
        event: 1004
    action:
      service: light.turn_off
      entity_id: all

  - alias: 'IKEA power switch'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: ikea_switch
        event: 1002
    action:
      service: light.toggle
      entity_id: light.living_room

  - alias: 'IKEA brightness up switch'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: ikea_switch
        event: 2002
    action:
      service: light.turn_on
      data:
        entity_id: light.living_room
        transition: '1'
        brightness_step_pct: 25

  - alias: 'IKEA brightness down switch'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: ikea_switch
        event: 3002
    action:
      service: light.turn_on
      data:
        entity_id: light.living_room
        transition: '1'
        brightness_step_pct: -25

  - alias: 'IKEA left switch'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: ikea_switch
        event: 4002
    action:
      service: switch.turn_off
      entity_id: switch.electric_blanket

  - alias: 'IKEA right switch'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: ikea_switch
        event: 5002
    action:
      - service: homeassistant.turn_on
        entity_id: group.fancybedroom
      - service: light.turn_on
        data:
          entity_id: light.living_room
          transition: '1'
          brightness_pct: 25

# Turns on lights if it's dark and people are home
# and if people get home between 16:00-03:00
  - alias: 'Light on in the evening'
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 5
      - platform: state
        entity_id: group.anyone
        to: 'home'
    condition:
      - condition: state
        entity_id: group.anyone
        state: 'home'
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 5
    action:
      service: scene.turn_on
      entity_id: scene.livingroom_normal

# Turn off lights and heating when everybody leaves the house
  - alias: 'Away Mode'
    trigger:
      platform: state
      entity_id: group.anyone
      from: 'home'
    action:
      - service: light.turn_off
        entity_id: all
      - service: climate.set_temperature
        data:
          entity_id: climate.house_heating
          temperature: 5
      

# Brightens/Dims lights when Chromecast is playing.
  - alias: "Media player paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.dave_chromecast
        from: 'playing'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: device_tracker.848edf2de6f5
        state: 'home'
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_normal

  - alias: "Media player playing"
    trigger:
      - platform: state
        entity_id: media_player.dave_chromecast
        to: 'playing'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: device_tracker.848edf2de6f5
        state: 'home'
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_dim
        
  - alias: Turn on downstairs hall light when there is movement
    trigger:
      platform: state
      entity_id: binary_sensor.downstairs_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 3
    action:
      service: homeassistant.turn_on
      entity_id: light.downstairs_hall

  - alias: Turn off downstairs light 1 minute after last movement
    trigger:
      platform: state
      entity_id: binary_sensor.downstairs_motion
      to: 'off'
      for:
        minutes: 1
    action:
      service: homeassistant.turn_off
      entity_id: light.downstairs_hall
        
  - alias: Turn on dressing room light when there is movement
    trigger:
      platform: state
      entity_id: binary_sensor.presence_15
      to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.dressing_room_light

  - alias: Turn off dressing room light after last movement
    trigger:
      platform: state
      entity_id: binary_sensor.presence_15
      to: 'off'
      for:
        minutes: 1
    action:
      service: homeassistant.turn_off
      entity_id: light.dressing_room_light
        
  - alias: Turn on kitchen light when there is movement
    trigger:
      platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 5
    action:
      - service: deconz.configure
        data:
          field: "/lights/00:15:8d:00:02:46:0d:4c-03/state"
          data: {"on":true}
      - service: device_tracker.see
        data:
          dev_id: "d07714205813"
          location_name: "home"


  - alias: Turn off kitchen light 1 minute after last movement
    trigger:
      platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
      for:
        minutes: 1
    action:
      service: deconz.configure
      data:
        field: "/lights/00:15:8d:00:02:46:0d:4c-03/state"
        data: {"on":false}
      
  - alias: Turn on upstairs hall light when there is movement
    trigger:
      platform: state
      entity_id: binary_sensor.upstairs_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 3
    action:
      service: scene.turn_on
      data_template:
        entity_id: >
          {%- if is_state('sensor.day_night', 'Night') %}
            scene.upstairs_hall_dim      
          {%- else %}
            scene.upstairs_hall_normal
          {% endif %}

  - alias: Turn off upstairs light 1 minute after last movement
    trigger:
      platform: state
      entity_id: binary_sensor.upstairs_motion
      to: 'off'
      for:
        minutes: 1
    action:
      service: homeassistant.turn_off
      entity_id: light.upstairs_hall

  - alias: Turn on bedside light when there is movement
    trigger:
      platform: state
      entity_id: binary_sensor.upstairs_motion
      to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: light.bedside_light
      - service: homeassistant.turn_off
        entity_id: automation.turn_on_bedside_light_when_there_is_movement

  - alias: Turn off upstairs light 1 minute after last movement
    trigger:
      platform: state
      entity_id: binary_sensor.upstairs_motion
      to: 'off'
      for:
        minutes: 1
    action:
      service: homeassistant.turn_off
      entity_id: light.upstairs_hall
      
  - alias: Bathroom heating on
    trigger:
      platform: time
      at: '06:00:00'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: numeric_state
        entity_id: 'sensor.weather_temperature'
        below: '5'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.bathroom_heating
          temperature: 15

  - alias: Bathroom heating off
    trigger:
      platform: time
      at: '07:00:00'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.bathroom_heating
          temperature: 5
      
  - alias: House Heating On
    trigger:
      - platform: time        
        at: '08:30:00'
      - platform: state
        entity_id: group.all_devices
        to: 'home'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: time
        after: '08:30:00'
        before: '20:00:00'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.house_heating
          temperature: 15

  - alias: House heating off
    trigger:
      platform: time
      at: '21:00:00'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.house_heating
          temperature: 5
