homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 48
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  base_url: !secret base_url
  server_port: 443
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 5
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Weather
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - cloudiness
  - platform: template
    sensors:
      day_night:
        friendly_name: "Day and night"
        value_template: >-
          {% if now().hour >= 18 and now().hour < 24 %}
            Evening
          {% elif now().hour >= 0 and now().hour < 6 %}  
            Night
          {% else %}
            Day
          {% endif %}

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#logger:

wake_on_lan:

hdmi_cec:
  devices:
    tv: 0.0.0.0
    fayes_pc: 1.0.0.0
    chromecast: 2.0.0.0
    hassio: 3.0.0.0
    
switch:
  - platform: wake_on_lan
    name: "Just Faye's PC"
    host: 192.168.0.11
    mac_address: "f4:6d:04:48:9f:9c"
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: fayes_pc
    
  - platform: wake_on_lan
    name: "My PC"
    mac_address: "50:e5:49:ec:a1:0c"
    host: 192.168.0.5
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: daves_pc
            
  - platform: template
    switches:
      telly:
        friendly_name: "The TV"
        value_template: "{{ is_state('switch.hdmi_0', 'on') }}"
        turn_on:
          service: script.television_on
        turn_off:
          service: script.television_off
          
  - platform: template
    switches:
      fayes_pc_and_tv:
        friendly_name: "Faye's PC"
        value_template: "{{ is_state('switch.just_fayes_pc', 'on') }}"
        turn_on:
          service: script.boot_to_fayes
        turn_off:
          service: script.turn_off_fayes
          
            
emulated_hue:
  host_ip: 192.168.0.4
  listen_port: 8300
  expose_by_default: false

alexa:

intent_script: !include alexa_intents.yaml

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.2
    home_interval: 10
  - platform: nmap_tracker
    hosts: 192.168.0.9
    home_interval: 10
    
automation old:
# Turns on lights if it's dark and people are home
# and if people get home between 16:00-03:00
  - alias: 'Light on in the evening'
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 5
      - platform: state
        entity_id: group.all_devices
        to: 'home'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: time
        after: '16:00:00'
        before: '03:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.livingroom_normal

# Turn off lights when everybody leaves the house
  - alias: 'Away Mode'
    trigger:
      platform: state
      entity_id: group.all_devices
      to: 'not_home'
    action:
      service: light.turn_off
      entity_id: group.all_lights
      

# Brightens/Dims lights when Chromecast is playing.
  - alias: "Media player paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.dave_chromecast
        from: 'playing'
#        to: 'idle'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: device_tracker.848edf2de6f5
        state: 'home'
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_normal

  - alias: "Media player playing"
    trigger:
      - platform: state
        entity_id: media_player.dave_chromecast
        to: 'playing'
#        from: 'idle'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: device_tracker.848edf2de6f5
        state: 'home'
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_dim
        
  - alias: Turn on downstairs hall light when there is movement
    trigger:
      platform: state
      entity_id: binary_sensor.presence_7
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 3
    action:
      service: homeassistant.turn_on
      entity_id: light.light_1

  - alias: Turn off downstairs light 30 seconds after last movement
    trigger:
      platform: state
      entity_id: binary_sensor.presence_7
      to: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: light.light_1
      
  - alias: Turn on upstairs hall light when there is movement
    trigger:
      platform: state
      entity_id: binary_sensor.presence_5
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 3
    action:
      service: scene.turn_on
      data_template:
        entity_id: >
          {%- if is_state('sensor.day_night', 'Night') %}
            scene.upstairs_hall_dim      
          {%- else %}
            scene.upstairs_hall_normal
          {% endif %}

  - alias: Turn off upstairs light 30 seconds after last movement
    trigger:
      platform: state
      entity_id: binary_sensor.presence_5
      to: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: light.upstairs_hall
      
  - alias: Bathroom heating on
    trigger:
      platform: time
      at: '07:30:00'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: numeric_state
        entity_id: 'sensor.weather_temperature'
        below: '5'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.heatmiser_wifi
          temperature: 15

  - alias: Bathroom heating off
    trigger:
      platform: time
      at: '08:30:00'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.heatmiser_wifi
          temperature: 5
          

 
climate:
  - platform: heatmiserWIFI
    ipaddress: 192.168.0.12
    port: 8068
    pin: !secret thermostat_pin

history_graph:
  gr1:
    name: Living Room Temperature
    entities:
      - sensor.temperature_1
    hours_to_show: 240
    refresh: 480